name: Build + Test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: [ubuntu-latest]

    name: Build Material Icon Theme

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup Bun ğŸ› ï¸
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2
        with:
          bun-version: 1.1.18

      - name: Cache Bun dependencies ğŸ“¦
        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4
        with:
          path: |
            ~/.bun/install/cache
          key: ${{ runner.os }}-bun-cache-${{ hashFiles('**/bun.lockb') }}

      - name: Install dependencies ğŸ“¦
        run: bun install --frozen-lockfile

      - name: Test + Build ğŸš€
        run: |
          bun test
          bun run vscode:prepublish
