name: ğŸ› ï¸ Build + Test

on:
  push:
    paths:
      - 'build/**'
      - 'icons/*.svg'
      - 'patches/**'
      - 'src/**'
      - '.bun-version'
      - 'bunfig.toml'
      - 'package.json'
      - 'sheriff.config.ts'
      - '!*.md'

  pull_request:
    paths:
      - 'build/**'
      - 'icons/*.svg'
      - 'patches/**'
      - 'src/**'
      - '.bun-version'
      - 'bunfig.toml'
      - 'package.json'
      - 'sheriff.config.ts'
      - '!*.md'

permissions:
  contents: read
  pull-requests: write
  issues: write # Update issue labels

jobs:
  build-and-test:
    name: Build & Test Extension

    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: ğŸ”§ Setup Bun
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2
        with:
          bun-version-file: ".bun-version"

      - name: ğŸ“¦ Install dependencies
        run: bun install --frozen-lockfile

      - name: ğŸš€ Test + Build
        id: build
        run: |
          bun test
          bun run vscode:prepublish

      - name: ğŸ·ï¸ Manage label based on build result
        if: ${{ always() && github.event_name == 'pull_request' }}
        uses: material-extensions/add-labels@60e0e247ae419e306ff73fff891bbf9bcf7d85c4 # v1.0.5
        with:
          labels: "âŒ failed build"
          action: ${{ steps.build.outcome == 'failure' && 'add' || 'remove' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
