name: ğŸ¨ Check SVG icon colors

on:
  pull_request:
    paths:
      - "icons/*.svg"

permissions:
  contents: read
  pull-requests: write
  issues: write # Update issue labels

jobs:
  color-check:
    name: SVG Color Check

    runs-on: ubuntu-latest

    env:
      TARGET_BRANCH: ${{ github.event.pull_request.base.ref }}

    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            .github/scripts/update-status-label.sh
            material-colors.yml
            icons/

      - name: ğŸ”„ Fetch target branch
        run: |
          git fetch origin $TARGET_BRANCH

      - name: ğŸ¨ Check colors
        id: color-check
        run: |
          svgFiles=$(git diff origin/$TARGET_BRANCH --diff-filter=ACMRTUX  --name-only | grep '.svg$')
          npx svg-color-linter --config material-colors.yml ${svgFiles}

      - name: ğŸ·ï¸ Manage label based on color check result
        if: always()
        run: .github/scripts/update-status-label.sh ${{ github.event.pull_request.number }} ${{ steps.color-check.outcome }} "ğŸ¨ invalid colors"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
