name: ğŸ‰ PR closed

on:
  pull_request:
    types:
      - closed

permissions:
  contents: read
  pull-requests: write

jobs:
  thank-you:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true

    steps:
      - name: ğŸ™ Post Thank You Comment
        uses: material-extensions/workflows/.github/workflows/pr-closed.yml@main
        with:
          comment: |
            ## Merge Successful

            Thanks for your contribution! ğŸ‰

            The changes will be part of the upcoming update on the Marketplace.`
