name: ðŸŽ‰ PR closed

on:
  pull_request:
    types:
      - closed

permissions:
  contents: read
  pull-requests: write

jobs:
  thank-you:
    if: github.event.pull_request.merged == true

    uses: material-extensions/workflows/.github/workflows/pr-closed.yml@main
    with:
      comment: |
        ## Merge Successful

        Thanks for your contribution! ðŸŽ‰

        The changes will be part of the upcoming update on the Marketplace.
