name: PR closed

on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout review-images branch ğŸ›ï¸
      uses: actions/checkout@v4
      with:
        ref: review-images

    - name: Delete PR related files ğŸ—‘ï¸
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          const dir = './review-images';
          const prNumber = context.payload.pull_request.number;

          fs.readdirSync(dir).forEach(file => {
            if (file.startsWith(`${prNumber}_`)) {
              fs.unlinkSync(path.join(dir, file));
            }
          });

    - name: Commit changes â¬†ï¸
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if [[ $(git diff --stat --staged) != '' ]]; then
          git commit -m "Delete files related to PR #${{ github.event.pull_request.number }}"
          git push
        fi

  thank_you:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Post Thank You Comment ğŸ™
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Merge Successful 
              
              Thanks for your contribution! ğŸ‰ 
              
              The changes will be part of the upcoming update on the marketplace.`
            })