name: âœ… Check PR Title

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  lint-pr-title:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ”§ Setup Bun
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2
        with:
          bun-version-file: ".bun-version"

      - name: ğŸ“¥ Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # only fetch the config file from the repository
          sparse-checkout: commitlint.config.js

      - name: ğŸ“¦ Install dependencies
        run: bun i @commitlint/config-conventional

      - name: ğŸ” Check PR title with commitlint
        run: echo "${{ github.event.pull_request.title }}" | bunx commitlint

      - name: ğŸ›‘ Fail if PR title is incorrect
        if: failure()
        run: |
          echo "Please make sure your PR title follows the Conventional Commit format."
          echo "Examples: 'feat: add new feature', 'fix: correct bug', 'docs: update documentation'."
